name: Prerelease2
on:
  workflow_dispatch:
  push:
    branches:
      - dev-next
      - debug
jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { type: "WithCGO", cc: "x86_64-w64-mingw32-gcc", goos: "windows", goarch: "amd64", goarm: "", name: sing-box-windows-4.0-amd64, id: "1" }
          - { type: "WithCGO", cc: "i686-w64-mingw32-gcc", goos: "windows", goarch: "386", goarm: "", name: sing-box-windows-4.0-386, id: "2" }

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Initialization environment
        run: |
          sudo apt -y update
          sudo apt -y install curl git build-essential libssl-dev libevent-dev zlib1g-dev gcc-mingw-w64
      
      - name: Set ENV
        run: |
          echo "NAME=sing-box" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "ShortSHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
        shell: bash

      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.version.outputs.go_version }}
          check-latest: true
      
      - name: Test
        if: ${{ github.ref_name=='debug' && matrix.job.id=='1' && matrix.job.type=='WithoutCGO' }}
        run: |
          go test -v ./...

      - name: Build WithoutCGO
        if: ${{ matrix.job.type=='WithoutCGO' }}
        env:
          NAME: sing-box
          TAGS: with_gvisor
        run: make -j$(($(nproc) + 1)) ${{ matrix.job.target }}

      - uses: nttld/setup-ndk@v1
        if: ${{ matrix.job.type=='WithCGO' && matrix.job.target=='android-arm-7' }}
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false
          local-cache: true

      - name: Build Android
        if: ${{ matrix.job.type=='WithCGO' && matrix.job.target=='android-arm-7' }}
        env:
          #ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          TAGS: with_gvisor,with_quic,with_wireguard,with_grpc,with_ech,with_utls,with_shadowsocksr,with_acme,with_clash_api,with_v2ray_api,with_embedded_tor,with_lwip
          LDFLAGS: -s -w -buildid=
          CGO_ENABLED: 1
          CC: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang
          GOARCH: arm
          GOOS: android
          GOARM: 7
          NAME: sing-box
        run: |
          mkdir dist
          CGO_ENABLED=$(CGO_ENABLED) CC=$(CC) GOOS=$(GOOS) GOARCH=$(GOARCH) GOARM=$(GOARM) go build -v -trimpath -tags "$(TAGS)" -ldflags "${LDFLAGS}" -o dist/${NAME}-android-arm-7 ./cmd/sing-box

      - name: Build by gcc
        if: ${{ matrix.job.type=='WithCGO' && matrix.job.target!='android-arm-7' }}
        env:
          #ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          TAGS: with_gvisor,with_quic,with_wireguard,with_grpc,with_ech,with_utls,with_shadowsocksr,with_acme,with_clash_api,with_v2ray_api,with_embedded_tor,with_lwip
          LDFLAGS: -s -w -buildid=
          CGO_ENABLED: 1
          #CC: x86_64-w64-mingw32-gcc
          #GOARCH: amd64
          #GOOS: windows
          #NAME: sing-box-windows-4.0-amd64
        run: |
          mkdir dist
          CGO_ENABLED=1 CC=${{ matrix.job.cc }} GOOS=${{ matrix.job.goos }} GOARCH=${{ matrix.job.goarch }} GOARM=${{ matrix.job.goarm }} go build -v -trimpath -tags "$(TAGS)" -ldflags "${LDFLAGS}" -o dist/${{ matrix.job.name }} ./cmd/sing-box

      - name: Rename
        if: ${{ matrix.job.type=='WithCGO' }}
        run: |
          cd dist
          ls -la
          cp ../.github/rename-cgo.sh ./
          bash ./rename-cgo.sh
          rm ./rename-cgo.sh
          ls -la
          cd ..
      - name: Zip
        if: ${{  success() }}
        run: |
          cd dist
          ls -la
          chmod +x *
          cp ../.github/release.sh ./
          bash ./release.sh
          rm ./release.sh
          ls -la
          cd ..
      - uses: actions/upload-artifact@v3
        if: ${{  success() }}
        with:
          name: artifact
          path: dist/

  Upload:
    permissions: write-all
    needs: [ Build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: dev-next-${{ github.ref_name }}
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.6
        with:
          tag_name: dev-next-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag: ${{ github.ref_name }}
          tag_name: dev-next-${{ github.ref_name }}
          files: dist/*
          prerelease: true
          generate_release_notes: true
